### ISSUE TITLE
OS Snapshot support

### ISSUE THREAD

**Issue by spinto** [EGI-FCTF/rOCCI-server#12]
Snapshot/backup of a OS image to be implemented into rOCCI server.

This feature requirements are:
- Give the user the possibility to save a VM disk image as a new OS template to be used as OS disk for a new VM
- OS template should be private and executable only by the user
- It is desired (but not mandatory) that the backup/snapshot operation is performed while the is still VM running.

**Comment by arax** [comment]
Fixed in #143
