### ISSUE TITLE
Doubt about authentication using rOCCI

### ISSUE THREAD

**Issue by giovannifs** [EGI-FCTF/rOCCI-server#130]
Hi all,

I'd like to understand better the authentication method used by rOCCI. 
When I'm using Keystone authentication, the rOCCI does a HEAD call at /-/ endpoint, gets the www-Authenticate header, gets a token from there, and lastly uses this token for calling the command at specific endpoint. If my understanding is right, the rOCCI also communicates with cloud for getting a token using VOMs.

Then, my doubt is: I wouldn't like to create a token at execution time, is it possible inform the token (one that would be created by communication between rOCCI and cloud) directly to rOCCI?

I'd appreciate your help.

**Comment by arax** [comment]
Hi @giovannifs,

at the moment, it is not possible to give rOCCI-cli/rOCCI-api a pre-generated token. If you would like to see this functionality in the next major release, please, open an "issue" (feature request :)) on [rOCCI-cli](https://github.com/EGI-FCTF/rOCCI-cli/issues).

Cheers

**Comment by giovannifs** [comment]
Hi @arax,

Thank you for your help. I'll do that.
