### ISSUE TITLE
rOCCI

### ISSUE THREAD

**Issue by jakofdarts** [EGI-FCTF/rOCCI-server#139]
Hi everyone,

I'm trying to make rOCCI server work with OpenNebula 4.12. 
I tried both version 1.1.9 and 1.1.8 but they cause me the same problem.

I performed the installation as expalined at: [https://wiki.egi.eu/wiki/rOCCI:ROCCI-server_Admin_Guide#Authentication_Drivers_in_OpenNebula ](url) 

Then I want to check the installation browsing https://my_ipervisor:11443 but I get the following message:

Authentication failed! The following strategies are supported "voms, x509, basic"!

I used this command to check what is going on: tcpdump -i lo tcp port 2633 -nvvv
and see this line among the output:

<?xml version="1.0" ?><methodCall><methodName>one.userpool.info</methodName><params><param><value><string>**rocci:correct_password**</string></value></param></params></methodCall>UwW??BE4??@@w?

so the session string seems to be ok.

I'm not a rOCCI expert user so I hope I've been clear enough. Please let me know if any other information is needed.

Many thanks,

Jacopo

**Comment by arax** [comment]
Hi Jacopo,
no worries, we will figure this out :-)

Firstly, I have a few questions.

* Did you install the server from packages or manually from source?
* Are you running with Apache2 as the application server?
* How is the `rocci` account configured in OpenNebula?  With the `server_cipher` auth driver and `oneadmin` group?
* Which authentication would you like to use with rOCCI-server? In other words, which type of credentials are you providing when accessing the rOCCI-server endpoint?
* Can you see something relevant/interesting in rOCCI-server's log or Apache2 error log?

**Comment by jakofdarts** [comment]
I add my colleague in cc who may help and give more detailed answers than me.
> Did you install the server from packages or manually from source?
I installed in from the packages.
> Are you running with Apache2 as the application server?
Yes.
> How is the rocci account configured in OpenNebula? With the server_cipher auth driver and oneadmin group?
I guess so. I used the command: oneuser create rocci password --driver server_cipher

> Which authentication would you like to use with rOCCI-server? In other words, which type of credentials are you providing when accessing the rOCCI-server endpoint?
I think a user/password authentication, don’t know if that was the question. 
> Can you see something relevant/interesting in rOCCI-server's log or Apache2 error log?
I had a look at the logs but the only thing I can see is that the authentication failed


Many thanks,

Jacopo

**Comment by arax** [comment]
> I guess so. I used the command: oneuser create rocci password --driver server_cipher

Did you also use the `chgrp`
