### ISSUE TITLE
EC2 Backend: network_delete_all() will (almost) always fail

### ISSUE THREAD

**Issue by sustr4** [EGI-FCTF/rOCCI-server#94]
Unless filtered, "all" includes the two default AWS networks ('private' & 'public') and the call to network_delete_all() will always fail with:

Backends::Errors::UserNotAuthorizedError:
       You cannot delete EC2-provided networks! ["public"]

I'll cross-assign this for confirmation. Please assign back to me for fix ;-)

**Comment by arax** [comment]
Confirmed. `NETWORK_DUMMIES` should be removed from `vpc_ids` before calling `network_delete(vpc_id)` or skipped.

**Comment by arax** [comment]
Fixed in EGI-FCTF/rOCCI-server#96
